ARG NODE_VERSION=24.14.0-alpine
FROM node:${NODE_VERSION} AS dev

WORKDIR /app

COPY . .

COPY package*.json ./
RUN npm install

USER node

EXPOSE 5173
CMD ["npm", "run" , "dev", "--", "--host", "0.0.0.0"]