ARG NODE_VERSION=24.14.0-alpine
FROM node:${NODE_VERSION} AS dev


WORKDIR /app

RUN mkdir -p /app/node_modules && chown node:node /app/node_modules
USER node

COPY --chown=node:node package.json package-lock.json* ./
RUN npm install

COPY --chown=node:node . .

EXPOSE 5173
CMD ["npm", "run" , "dev", "--", "--host", "0.0.0.0"]