include:
  - env_file: ./.env.prod

name: website-gamux
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - private_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - frontend
      - backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-5173}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - public_network
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    image: gamux/api-gamux:latest
    container_name: backend_service
    restart: always
    env_file:
      - .env.prod
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - private_network
      - public_network
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: gamux/website-gamux:latest
    container_name: frontend_service
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    networks:
      - public_network
  
networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge

volumes:
  pgdata: