FROM maven:3.9.11-eclipse-temurin-25 AS build
WORKDIR /app 

COPY .mvn/ .mvn 
COPY mvnw pom.xml ./ 

RUN sed -i 's/\r$//' mvnw && chmod +x mvnw 

RUN ./mvnw dependency:go-offline 

COPY src ./src 

CMD ["sh", "./mvnw", "spring-boot:run"]