spring.application.name=website-api
spring.flyway.enabled=false
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/${DB_NAME:gamuxdb}}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}